// shared e2e helpers: synthetic media fixtures + app interaction utilities.
//
// committed fixtures live in e2e/fixtures/ (WAV + PNG, generated by
// generate.mjs and tracked in git). use loadCommittedAudioFixtures() /
// loadCommittedImageFixtures() to reference them by name.
//
// user-provided fixtures (real music/images) go in e2e/fixtures/user-provided/
// (gitignored except README.md). loadRealAudioFixtures() scans both dirs.

import { readdirSync, readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { expect, type Page } from "@playwright/test";

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), "fixtures");
const USER_PROVIDED_DIR = join(FIXTURES_DIR, "user-provided");

// --- timestamped logging ---

// log with a wall-clock timestamp so slow steps and stalls are visible
// in test output (e.g. "[12:34:56] [e2e] peer a: p2p node online")
export function logTs(message: string): void {
  const now = new Date().toTimeString().slice(0, 8);
  console.log(`[${now}] ${message}`);
}

// --- synthetic audio ---

// build a valid mono 16-bit PCM WAV file with a sine tone.
// durationSec controls both file size and the decoded duration shown in the UI.
export function makeWav(durationSec = 1, freqHz = 440): Uint8Array {
  const sampleRate = 8000;
  const numSamples = Math.floor(sampleRate * durationSec);
  const dataSize = numSamples * 2;
  const buf = new ArrayBuffer(44 + dataSize);
  const view = new DataView(buf);
  const writeStr = (offset: number, s: string) => {
    for (let i = 0; i < s.length; i++) view.setUint8(offset + i, s.charCodeAt(i));
  };
  writeStr(0, "RIFF");
  view.setUint32(4, 36 + dataSize, true);
  writeStr(8, "WAVE");
  writeStr(12, "fmt ");
  view.setUint32(16, 16, true); // fmt chunk size
  view.setUint16(20, 1, true); // PCM
  view.setUint16(22, 1, true); // mono
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 2, true); // byte rate
  view.setUint16(32, 2, true); // block align
  view.setUint16(34, 16, true); // bits per sample
  writeStr(36, "data");
  view.setUint32(40, dataSize, true);
  for (let i = 0; i < numSamples; i++) {
    const sample = Math.sin((2 * Math.PI * freqHz * i) / sampleRate);
    view.setInt16(44 + i * 2, Math.floor(sample * 0x4fff), true);
  }
  return new Uint8Array(buf);
}

// --- synthetic images ---

// generate a real PNG in the page via canvas (solid color + label text).
// returns the bytes so they can be dropped or set on file inputs.
export async function makePng(
  page: Page,
  opts: { width?: number; height?: number; color?: string; label?: string } = {}
): Promise<Uint8Array> {
  const { width = 64, height = 64, color = "#ff00ff", label = "" } = opts;
  const base64 = await page.evaluate(
    async ({ width, height, color, label }) => {
      const canvas = document.createElement("canvas");
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext("2d")!;
      ctx.fillStyle = color;
      ctx.fillRect(0, 0, width, height);
      if (label) {
        ctx.fillStyle = "#000";
        ctx.font = "12px monospace";
        ctx.fillText(label, 4, height / 2);
      }
      const blob: Blob = await new Promise((res) =>
        canvas.toBlob((b) => res(b!), "image/png")
      );
      const bytes = new Uint8Array(await blob.arrayBuffer());
      let bin = "";
      for (const b of bytes) bin += String.fromCharCode(b);
      return btoa(bin);
    },
    { width, height, color, label }
  );
  return Uint8Array.from(Buffer.from(base64, "base64"));
}

// --- real fixtures ---

export interface FixtureFile {
  name: string;
  mimeType: string;
  bytes: Uint8Array;
}

const AUDIO_EXT: Record<string, string> = {
  ".mp3": "audio/mpeg",
  ".wav": "audio/wav",
  ".flac": "audio/flac",
  ".ogg": "audio/ogg",
  ".m4a": "audio/mp4",
};

const IMAGE_EXT: Record<string, string> = {
  ".png":  "image/png",
  ".jpg":  "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
};

function loadAudioDir(dir: string): FixtureFile[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => Object.keys(AUDIO_EXT).some((ext) => f.toLowerCase().endsWith(ext)))
    .map((f) => {
      const ext = Object.keys(AUDIO_EXT).find((e) => f.toLowerCase().endsWith(e))!;
      return {
        name: f,
        mimeType: AUDIO_EXT[ext]!,
        bytes: new Uint8Array(readFileSync(join(dir, f))),
      };
    });
}

function loadImageDir(dir: string): FixtureFile[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => Object.keys(IMAGE_EXT).some((ext) => f.toLowerCase().endsWith(ext)))
    .map((f) => {
      const ext = Object.keys(IMAGE_EXT).find((e) => f.toLowerCase().endsWith(e))!;
      return {
        name: f,
        mimeType: IMAGE_EXT[ext]!,
        bytes: new Uint8Array(readFileSync(join(dir, f))),
      };
    });
}

// committed audio fixtures (WAV sine waves, generated by generate.mjs).
// always available; never returns [].
export function loadCommittedAudioFixtures(): FixtureFile[] {
  return loadAudioDir(FIXTURES_DIR);
}

// committed image fixtures (PNG patterns, generated by generate.mjs).
// always available; never returns [].
export function loadCommittedImageFixtures(): FixtureFile[] {
  return loadImageDir(FIXTURES_DIR);
}

// load all audio files from both committed fixtures and user-provided/.
// user-provided/ is gitignored so returns [] when not present.
export function loadRealAudioFixtures(): FixtureFile[] {
  return [
    ...loadAudioDir(FIXTURES_DIR),
    ...loadAudioDir(USER_PROVIDED_DIR),
  ];
}

// load all image files from both committed fixtures and user-provided/.
export function loadRealImageFixtures(): FixtureFile[] {
  return [
    ...loadImageDir(FIXTURES_DIR),
    ...loadImageDir(USER_PROVIDED_DIR),
  ];
}

// --- app interaction helpers ---

// drop files onto the app (simulates drag and drop of audio files / zips).
export async function dropFiles(page: Page, files: FixtureFile[]): Promise<void> {
  const payload = files.map((f) => ({
    name: f.name,
    mimeType: f.mimeType,
    base64: Buffer.from(f.bytes).toString("base64"),
  }));
  await page.evaluate(async (payload) => {
    const dt = new DataTransfer();
    for (const f of payload) {
      const bin = atob(f.base64);
      const bytes = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
      dt.items.add(new File([bytes], f.name, { type: f.mimeType }));
    }
    const target = document.querySelector('[data-testid="app-root"]') ?? document.body;
    target.dispatchEvent(
      new DragEvent("drop", { bubbles: true, cancelable: true, dataTransfer: dt })
    );
  }, payload);
}

// wipe all app storage (indexeddb + localstorage) and reload for a clean slate.
export async function resetAppState(page: Page): Promise<void> {
  await page.goto("/");
  await page.evaluate(async () => {
    localStorage.clear();
    const dbs = await indexedDB.databases();
    await Promise.all(
      dbs.map(
        (db) =>
          new Promise<void>((res) => {
            if (!db.name) return res();
            const req = indexedDB.deleteDatabase(db.name);
            req.onsuccess = req.onerror = req.onblocked = () => res();
          })
      )
    );
  });
  await page.reload();
  await waitForApp(page);
}

// wait for the app shell to finish booting
export async function waitForApp(page: Page): Promise<void> {
  await page.getByTestId("app-ready").waitFor({ timeout: 10000 });
}

// create a playlist via the UI and wait for the playlist header to appear.
// on a fresh app (no playlists): clicks the "new playlist" button in the empty state.
// if a playlist is already selected: opens the all-playlists panel via the
// hamburger and clicks "new playlist" there.
export async function createPlaylistViaUI(page: Page): Promise<void> {
  // try the always-visible empty-state button first, fall back to hamburger flow
  const newBtn = page.getByTestId("btn-new-playlist");
  const isVisible = await newBtn.isVisible().catch(() => false);
  if (isVisible) {
    await newBtn.click();
  } else {
    // open all-playlists panel via hamburger
    await page.getByTestId("btn-all-playlists").click();
    await page.getByTestId("btn-new-playlist").click();
  }
  await page.getByTestId("btn-edit-playlist").waitFor({ timeout: 5000 });
  // wait for the title input to reflect the new playlist's default title,
  // confirming the reactive binding is live before callers try to fill it
  await expect(page.getByTestId("input-playlist-title")).toHaveValue(
    "new playlist"
  );
}

// add n synthetic songs to the selected playlist via drag and drop
export async function addSongs(page: Page, count: number, durationSec = 1): Promise<void> {
  const files: FixtureFile[] = [];
  for (let i = 0; i < count; i++) {
    files.push({
      name: `song-${String(i).padStart(2, "0")}.wav`,
      mimeType: "audio/wav",
      bytes: makeWav(durationSec, 220 + i * 110),
    });
  }
  await dropFiles(page, files);
  // wait for the last row to show up
  await page
    .getByText(`song-${String(count - 1).padStart(2, "0")}`)
    .waitFor({ timeout: 15000 });
}

// load a single committed fixture by filename
export function fixture(name: string): FixtureFile {
  const audio = AUDIO_EXT[`.${name.split(".").pop()!.toLowerCase()}`];
  const image = IMAGE_EXT[`.${name.split(".").pop()!.toLowerCase()}`];
  const mimeType = audio ?? image ?? "application/octet-stream";
  return {
    name,
    mimeType,
    bytes: new Uint8Array(readFileSync(join(FIXTURES_DIR, name))),
  };
}

// set a cover image on the playlist edit panel via the file input
export async function setPlaylistCover(page: Page, f: FixtureFile): Promise<void> {
  const input = page.locator("input[type='file']").first();
  await input.waitFor({ state: "attached", timeout: 5000 });
  await input.setInputFiles({ name: f.name, mimeType: f.mimeType, buffer: Buffer.from(f.bytes) });
}

// --- dev hook helpers ---
// typed wrappers around window.__* dev hooks (registered by src/dev-hooks.ts).
// use these in tests instead of raw page.evaluate calls.

// mock blob behaviour modes (mirrors MockBlobBehaviour in src/dev-hooks.ts)
export type MockBlobBehaviour =
  | { type: "instant" }
  | { type: "delayed"; ms: number }
  | { type: "progress"; chunks: number; msPerChunk: number }
  | { type: "error"; code: "not_found" | "timeout" | "peer_gone" }
  | { type: "stall" };

// seek the audio element to a specific time (seconds)
export async function seekTo(page: Page, seconds: number): Promise<void> {
  await page.evaluate((t) => window.__seekTo?.(t), seconds);
}

// fire the "ended" event on the audio element
export async function triggerTrackEnd(page: Page): Promise<void> {
  await page.evaluate(() => window.__triggerTrackEnd?.());
}

// fire an audio error event (code defaults to MEDIA_ERR_SRC_NOT_SUPPORTED = 4)
export async function triggerAudioError(page: Page, code = 4): Promise<void> {
  await page.evaluate((c) => window.__triggerAudioError?.(c), code);
}

// override p2p blob fetching with a deterministic mock behaviour
export async function mockBlobFetch(
  page: Page,
  behaviour: MockBlobBehaviour
): Promise<void> {
  await page.evaluate(
    (b) => window.__mockBlobFetch?.(b),
    behaviour as Parameters<NonNullable<typeof window.__mockBlobFetch>>[0]
  );
}

// restore real p2p blob fetching
export async function clearMockBlobFetch(page: Page): Promise<void> {
  await page.evaluate(() => window.__clearMockBlobFetch?.());
}

// remove a blob from local store (simulates a cache miss before pressing play)
export async function evictBlob(page: Page, sha256: string): Promise<void> {
  await page.evaluate((sha) => window.__evictBlob?.(sha), sha256);
}
