// synthetic media generation and fixture file loading.
//
// no Playwright Page imports here - everything is pure data or Node fs ops.
// used by both app helpers and spec files directly.

import { readdirSync, readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const FIXTURES_DIR = join(dirname(fileURLToPath(import.meta.url)), "../fixtures");
const USER_PROVIDED_DIR = join(FIXTURES_DIR, "user-provided");

// --- synthetic audio ---

// build a valid mono 16-bit PCM WAV file with a sine tone.
// durationSec controls both file size and the decoded duration shown in the UI.
export function makeWav(durationSec = 1, freqHz = 440): Uint8Array {
  const sampleRate = 8000;
  const numSamples = Math.floor(sampleRate * durationSec);
  const dataSize = numSamples * 2;
  const buf = new ArrayBuffer(44 + dataSize);
  const view = new DataView(buf);
  const writeStr = (offset: number, s: string) => {
    for (let i = 0; i < s.length; i++) view.setUint8(offset + i, s.charCodeAt(i));
  };
  writeStr(0, "RIFF");
  view.setUint32(4, 36 + dataSize, true);
  writeStr(8, "WAVE");
  writeStr(12, "fmt ");
  view.setUint32(16, 16, true); // fmt chunk size
  view.setUint16(20, 1, true); // PCM
  view.setUint16(22, 1, true); // mono
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 2, true); // byte rate
  view.setUint16(32, 2, true); // block align
  view.setUint16(34, 16, true); // bits per sample
  writeStr(36, "data");
  view.setUint32(40, dataSize, true);
  for (let i = 0; i < numSamples; i++) {
    const sample = Math.sin((2 * Math.PI * freqHz * i) / sampleRate);
    view.setInt16(44 + i * 2, Math.floor(sample * 0x4fff), true);
  }
  return new Uint8Array(buf);
}

// --- fixture file type ---

export interface FixtureFile {
  name: string;
  mimeType: string;
  bytes: Uint8Array;
}

const AUDIO_EXT: Record<string, string> = {
  ".mp3": "audio/mpeg",
  ".wav": "audio/wav",
  ".flac": "audio/flac",
  ".ogg": "audio/ogg",
  ".m4a": "audio/mp4",
};

const IMAGE_EXT: Record<string, string> = {
  ".png":  "image/png",
  ".jpg":  "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
};

function loadAudioDir(dir: string): FixtureFile[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => Object.keys(AUDIO_EXT).some((ext) => f.toLowerCase().endsWith(ext)))
    .map((f) => {
      const ext = Object.keys(AUDIO_EXT).find((e) => f.toLowerCase().endsWith(e))!;
      return {
        name: f,
        mimeType: AUDIO_EXT[ext]!,
        bytes: new Uint8Array(readFileSync(join(dir, f))),
      };
    });
}

function loadImageDir(dir: string): FixtureFile[] {
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => Object.keys(IMAGE_EXT).some((ext) => f.toLowerCase().endsWith(ext)))
    .map((f) => {
      const ext = Object.keys(IMAGE_EXT).find((e) => f.toLowerCase().endsWith(e))!;
      return {
        name: f,
        mimeType: IMAGE_EXT[ext]!,
        bytes: new Uint8Array(readFileSync(join(dir, f))),
      };
    });
}

// committed audio fixtures (WAV sine waves, generated by generate.mjs).
// always available; never returns [].
export function loadCommittedAudioFixtures(): FixtureFile[] {
  return loadAudioDir(FIXTURES_DIR);
}

// committed image fixtures (PNG patterns, generated by generate.mjs).
// always available; never returns [].
export function loadCommittedImageFixtures(): FixtureFile[] {
  return loadImageDir(FIXTURES_DIR);
}

// load all audio files from both committed fixtures and user-provided/.
// user-provided/ is gitignored so returns [] when not present.
export function loadRealAudioFixtures(): FixtureFile[] {
  return [...loadAudioDir(FIXTURES_DIR), ...loadAudioDir(USER_PROVIDED_DIR)];
}

// load all image files from both committed fixtures and user-provided/.
export function loadRealImageFixtures(): FixtureFile[] {
  return [...loadImageDir(FIXTURES_DIR), ...loadImageDir(USER_PROVIDED_DIR)];
}

// load a single committed fixture by filename
export function fixture(name: string): FixtureFile {
  const ext = `.${name.split(".").pop()!.toLowerCase()}`;
  const mimeType = AUDIO_EXT[ext] ?? IMAGE_EXT[ext] ?? "application/octet-stream";
  return { name, mimeType, bytes: new Uint8Array(readFileSync(join(FIXTURES_DIR, name))) };
}
